# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddd11d056274dc92a52e3a2721bc161bea05531f8d18fe9fee709c881ef7a793ed4d1dec5a15770e2b505e3a5e93fcb754a8162b54b7d278f0ca75433e6f244a

test:
  secret_key_base: 2e1c5c9448f2ad907296c9cb78903ee32f451c68cfbdb61c9364b391c7b570f4bd1624109c878ac5f869ff9c436ca4e197257e475e7f5d4523db0f363e79ad7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
